name: Run Linter

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3 # pin@v2

      - name: setup python 3
        uses: actions/setup-python@v4 # pin@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: make getdeps && pip3 install -r requirements-dev.txt

      - name: run linter
        run: make lint
