name: Run Linter

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2

      - name: setup python 3
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: make getdeps && pip3 install -r requirements-dev.txt

      - name: run linter
        run: make lint
